import Head from 'next/head'
import Feed from '../components/Feed'
import Navbar from '../components/Navbar'
import { fetchProjects } from '../utils/fetchProjects'
import { fetchSkills } from '../utils/fetchSkills'
import { createContext } from 'react'




export default function Home({ skills, projects }) {
  const Data = createContext(
    {
      skills: skills,
      projects: projects
    });

  return (
    <div
      className='w-[100%] overflow-hidden'>
      <Head>
        <title>Mohamed El Fateh</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Data.Provider value={Data}>
        <Feed skills={skills} projects={projects} />
      </Data.Provider>
    </div>
  )
}

export const getServerSideProps = async (context) => {

  const [projects, skills] = await Promise.all([
    fetchProjects(),
    fetchSkills()
  ]);


  return {
    props: {
      skills
      , projects
    }
  }
}

